[workspace]
resolver = "2"
members = [
  "headlamp",
  "headlamp_tests",
  "headlamp_parity_tests",
  "headlamp_parity_support",
  "xtask",
  "treemap_viewer",
]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0
incremental = false
